import type{Database,Json}from"@/types/database";import type{EmploymentType,Job,JobEvaluation,JobPreferences,JobStatus,WorkArrangement}from"@/types/job";import{createClient}from"@/lib/supabase/server";import{evaluateEligibility}from"@/lib/ingestion/eligibility";
type JobRow=Database["public"]["Tables"]["jobs"]["Row"];
type PreferenceRow=Database["public"]["Tables"]["job_preferences"]["Row"];
export interface JobRepository{getJobs(userId:string):Promise<Job[]>;getJobById(id:string,userId:string):Promise<Job|undefined>;setStatus(userId:string,jobId:string,status:JobStatus):Promise<void>}
function evaluationFrom(raw:Json|null):JobEvaluation|undefined{if(!raw||Array.isArray(raw)||typeof raw!=="object")return;const value=raw.evaluation;if(!value||Array.isArray(value)||typeof value!=="object")return;return value as unknown as JobEvaluation}
function categoryFrom(raw:Json|null){return raw&&!Array.isArray(raw)&&typeof raw==="object"&&typeof raw.category==="string"?raw.category:"Other"}
function mapJob(row:JobRow,status:JobStatus="new"):Job{return{id:row.id,externalId:row.external_id??undefined,source:row.source,sourceUrl:row.source_url,applyUrl:row.application_url??undefined,company:row.company,title:row.title,description:row.description,category:categoryFrom(row.raw_payload),location:row.location,workArrangement:row.workplace_type as WorkArrangement|undefined,employmentType:row.employment_type as EmploymentType|undefined,salaryMin:row.salary_min??undefined,salaryMax:row.salary_max??undefined,salaryCurrency:row.salary_currency??undefined,compensationInterval:row.compensation_interval as Job["compensationInterval"],skills:row.skills,seniority:row.seniority??undefined,sponsorship:row.sponsorship??undefined,postedAt:row.posted_at??undefined,discoveredAt:row.discovered_at,status,isActive:row.is_active,evaluation:evaluationFrom(row.raw_payload)}}
function mapPreferences(row:PreferenceRow|null):JobPreferences{return{desiredTitles:row?.desired_titles??[],desiredLocations:row?.desired_locations??[],remotePreference:(row?.remote_preference??"flexible")as WorkArrangement|"flexible",employmentTypes:(row?.employment_types??[])as EmploymentType[],minimumSalary:row?.minimum_salary??null,preferredIndustries:row?.preferred_industries??[],preferredSkills:row?.preferred_skills??[],excludedKeywords:row?.excluded_keywords??[],sponsorshipRequired:row?.sponsorship_required??false}}
export function isVisibleInDiscovery(job:Job,preferences:JobPreferences){if(job.status==="rejected")return false;if(job.status==="saved"||job.status==="applied")return true;return evaluateEligibility(job,preferences).eligible}
export const supabaseJobRepository:JobRepository={async getJobs(userId){const supabase=await createClient();const[{data:jobs,error},{data:statuses,error:statusError},{data:preferences,error:preferencesError}]=await Promise.all([supabase.from("jobs").select("*").order("discovered_at",{ascending:false}),supabase.from("user_job_statuses").select("job_id,status").eq("user_id",userId),supabase.from("job_preferences").select("*").eq("user_id",userId).maybeSingle()]);if(error||statusError||preferencesError)throw new Error("Unable to load jobs right now.");const byId=new Map((statuses??[]).map(item=>[item.job_id,item.status as JobStatus])),mappedPreferences=mapPreferences(preferences);return(jobs??[]).map(row=>mapJob(row,byId.get(row.id))).filter(job=>isVisibleInDiscovery(job,mappedPreferences))},async getJobById(id,userId){const supabase=await createClient();const[{data,error},{data:status}]=await Promise.all([supabase.from("jobs").select("*").eq("id",id).maybeSingle(),supabase.from("user_job_statuses").select("status").eq("user_id",userId).eq("job_id",id).maybeSingle()]);if(error)throw new Error("Unable to load this job right now.");const job=data?mapJob(data,status?.status as JobStatus|undefined):undefined;return job?.status==="rejected"?undefined:job},async setStatus(userId,jobId,status){const supabase=await createClient();const{error}=await supabase.from("user_job_statuses").upsert({user_id:userId,job_id:jobId,status,applied_at:status==="applied"?new Date().toISOString():null},{onConflict:"user_id,job_id"});if(error)throw new Error("Your job status could not be saved.")}};
export const getJobs=(userId:string)=>supabaseJobRepository.getJobs(userId);export const getJobById=(id:string,userId:string)=>supabaseJobRepository.getJobById(id,userId);
