import test from"node:test";import assert from"node:assert/strict";import{candidateProfileHash,isEvaluationCacheValid}from"./candidate/hash";import{jobEvaluationSchema,resumeExtractionSchema}from"./ai/schemas";import{mayUseAiEvaluation,paginationRange}from"./evaluations/policy";import type{Job,JobPreferences}from"@/types/job";
import { importFingerprint,resumeImportPayload } from "./candidate/import";
test("candidate hash is stable across key and collection ordering",()=>{const a=candidateProfileHash({skills:["React","TypeScript"],profile:{name:" Ada  Lovelace "}}),b=candidateProfileHash({profile:{name:"Ada Lovelace"},skills:["TypeScript","React"]});assert.equal(a,b);assert.notEqual(a,candidateProfileHash({profile:{name:"Grace"},skills:["React","TypeScript"]}))});
test("cache validity requires all deterministic versions",()=>{const row={candidateProfileHash:"a",jobContentHash:"b",promptVersion:"v1"};assert.equal(isEvaluationCacheValid(row,{...row}),true);assert.equal(isEvaluationCacheValid(row,{...row,jobContentHash:"changed"}),false);assert.equal(isEvaluationCacheValid(row,{...row,candidateProfileHash:"changed"}),false);assert.equal(isEvaluationCacheValid(row,{...row,promptVersion:"v2"}),false)});
test("score schema enforces bounds and strict structured output",()=>{const base={overallScore:80,skillScore:80,experienceScore:80,educationScore:80,interestScore:80,locationScore:80,compensationScore:null,verdict:"strong",recommendation:"apply",summary:"Fit",matchingSkills:[],missingSkills:[],strengths:[],concerns:[],requirementGaps:[]};assert.equal(jobEvaluationSchema.parse(base).overallScore,80);assert.throws(()=>jobEvaluationSchema.parse({...base,overallScore:101}));assert.throws(()=>jobEvaluationSchema.parse({...base,extra:true}))});
test("mocked resume structured output maps without invented facts",()=>{const value=resumeExtractionSchema.parse({summary:null,skills:[{name:"TypeScript",proficiency:null,yearsExperience:null,confidence:"explicit"}],experiences:[],projects:[],education:[],links:{github:null,linkedin:null,portfolio:null},uncertainties:["Graduation month is unclear"]});assert.equal(value.skills[0].yearsExperience,null);assert.equal(value.uncertainties.length,1)});
const preferences:JobPreferences={desiredTitles:[],desiredLocations:[],remotePreference:"remote",employmentTypes:["internship"],minimumSalary:null,preferredIndustries:[],preferredSkills:[],excludedKeywords:[],sponsorshipRequired:false};const job:Job={id:"1",company:"Acme",title:"Intern",category:"Other",location:"Boston",description:"",discoveredAt:"2026-01-01",sourceUrl:"https://x",status:"new",isActive:true,workArrangement:"onsite",employmentType:"internship"};
test("hard eligibility prevents AI use",()=>assert.equal(mayUseAiEvaluation(job,preferences),false));test("pagination ranges are stable and capped",()=>{assert.deepEqual(paginationRange(2,50),{from:50,to:99,page:2,pageSize:50});assert.equal(paginationRange(1,500).pageSize,50)});
test("resume import fingerprints are deterministic",()=>{const experience={organization:" Acme ",title:"Engineer",startDate:"2025-01-01",endDate:null,isCurrent:true,location:null,description:"Built things",skills:["TypeScript","React"]};assert.equal(importFingerprint("experience",experience),importFingerprint("experience",{...experience,organization:"acme",skills:["React","TypeScript"]}));const extraction=resumeExtractionSchema.parse({summary:"Imported",skills:[],experiences:[experience],projects:[],education:[],links:{github:null,linkedin:null,portfolio:null},uncertainties:[]});const first=resumeImportPayload(extraction),second=resumeImportPayload(extraction);assert.equal(first.experiences[0].fingerprint,second.experiences[0].fingerprint)});
