import { createHash } from "node:crypto";
import type { CompensationInterval, EmploymentType, WorkArrangement } from "@/types/job";

export function textFromHtml(html:string):string{return html.replace(/<br\s*\/?\s*>/gi,"\n").replace(/<\/p>|<\/li>|<\/h\d>/gi,"\n").replace(/<[^>]*>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/[ \t]+/g," ").replace(/\n\s+/g,"\n").trim()}
export function normalizeEmployment(value?:string):EmploymentType|undefined{const v=value?.toLowerCase();if(!v)return;if(v.includes("intern"))return"internship";if(v.includes("part"))return"part-time";if(v.includes("contract")||v.includes("temporary"))return"contract";if(v.includes("full"))return"full-time"}
export function normalizeWorkplace(value?:string,location?:string):WorkArrangement|undefined{const v=`${value??""} ${location??""}`.toLowerCase();if(/\bhybrid\b/.test(v))return"hybrid";if(/\bremote\b/.test(v))return"remote";if(/on[ -]?site|in[ -]?office/.test(v))return"onsite"}
export function normalizeInterval(value?:string):CompensationInterval{const v=value?.toLowerCase();if(v?.includes("hour"))return"hourly";if(v?.includes("year")||v?.includes("annual"))return"yearly";if(v?.includes("month"))return"monthly";if(v?.includes("week"))return"weekly";return"unknown"}
export function contentHash(value:{company:string;title:string;location:string;url:string}){const canonical=[value.company,value.title,value.location,value.url].map(v=>v.trim().toLowerCase().replace(/\s+/g," ").replace(/\/$/,"")).join("\u001f");return createHash("sha256").update(canonical).digest("hex")}
export function inferSeniority(title:string){const v=title.toLowerCase();if(/\b(intern|co-op|new grad|entry level|junior)\b/.test(v))return"entry";if(/\b(senior|sr\.?|staff|principal|lead)\b/.test(v))return"senior"}
export function explicitSponsorship(text:string):boolean|undefined{const v=text.toLowerCase();if(/(unable|cannot|do not|won't|will not) (to )?(provide|offer|support).*sponsor|no (visa )?sponsorship/.test(v))return false;if(/visa sponsorship (is )?(available|provided)|will sponsor/.test(v))return true}
