import { createHash } from "node:crypto";
import type { CompensationInterval, EmploymentType, WorkArrangement } from "@/types/job";

export function textFromHtml(html:string):string{return html.replace(/<br\s*\/?\s*>/gi,"\n").replace(/<\/p>|<\/li>|<\/h\d>/gi,"\n").replace(/<[^>]*>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/[ \t]+/g," ").replace(/\n\s+/g,"\n").trim()}
export function normalizeEmployment(value?:string):EmploymentType|undefined{const v=value?.toLowerCase();if(!v)return;if(v.includes("intern"))return"internship";if(v.includes("part"))return"part-time";if(v.includes("contract")||v.includes("temporary"))return"contract";if(v.includes("full"))return"full-time"}
export function normalizeWorkplace(value?:string,location?:string):WorkArrangement|undefined{const v=`${value??""} ${location??""}`.toLowerCase();if(/\bhybrid\b/.test(v))return"hybrid";if(/\bremote\b/.test(v))return"remote";if(/on[ -]?site|in[ -]?office/.test(v))return"onsite"}
export function normalizeInterval(value?:string):CompensationInterval{const v=value?.toLowerCase();if(v?.includes("hour"))return"hourly";if(v?.includes("year")||v?.includes("annual"))return"yearly";if(v?.includes("month"))return"monthly";if(v?.includes("week"))return"weekly";return"unknown"}
export function contentHash(value:{company:string;title:string;description?:string;location:string;url?:string;workplaceType?:string;employmentType?:string;salaryMin?:number;salaryMax?:number;salaryCurrency?:string;compensationInterval?:string;skills?:string[];seniority?:string;sponsorship?:boolean}){const scalar=(v:string|number|boolean|undefined)=>String(v??"").trim().toLowerCase().replace(/\s+/g," "),canonical=[value.company,value.title,value.description??"",value.location,value.workplaceType??"",value.employmentType??"",value.salaryMin,value.salaryMax,value.salaryCurrency??"",value.compensationInterval??"",[...(value.skills??[])].map(scalar).sort().join(","),value.seniority??"",value.sponsorship].map(scalar).join("\u001f");return createHash("sha256").update(canonical).digest("hex")}
export function normalizeJobUrl(value:string){try{const url=new URL(value);url.hash="";for(const key of [...url.searchParams.keys()])if(/^utm_|^(source|ref|gh_src)$/i.test(key))url.searchParams.delete(key);url.pathname=url.pathname.replace(/\/+$/,"/");return url.toString()}catch{return value}}
const normalized=(value:string)=>value.trim().toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
export function canonicalJobKey(job:{company:string;title:string;location:string;employmentType?:string;description:string;applicationUrl?:string;sourceUrl:string}){const url=normalizeJobUrl(job.applicationUrl??job.sourceUrl);let host="";try{host=new URL(url).hostname.replace(/^www\./,"")}catch{}const employerUrl=/(greenhouse\.io|lever\.co|ashbyhq\.com|smartrecruiters\.com|recruitee\.com)$/.test(host)?url:"";return createHash("sha256").update(employerUrl||[job.company,job.title,job.location,job.employmentType??"unknown",createHash("sha256").update(normalized(job.description).slice(0,4000)).digest("hex")].map(normalized).join("\u001f")).digest("hex")}
export function selectCanonicalUrl(urls:{url:string;kind:"ats"|"careers"|"third-party"}[]){const weight={ats:3,careers:2,"third-party":1};return [...urls].sort((a,b)=>weight[b.kind]-weight[a.kind])[0]?.url}
export function inferSeniority(title:string){const v=title.toLowerCase();if(/\b(intern|co-op|new grad|entry level|junior)\b/.test(v))return"entry";if(/\b(senior|sr\.?|staff|principal|lead)\b/.test(v))return"senior"}
export function explicitSponsorship(text:string):boolean|undefined{const v=text.toLowerCase();if(/(unable|cannot|do not|won't|will not) (to )?(provide|offer|support).*sponsor|no (visa )?sponsorship/.test(v))return false;if(/visa sponsorship (is )?(available|provided)|will sponsor/.test(v))return true}
