export type Json=string|number|boolean|null|{[key:string]:Json|undefined}|Json[];
type Status="new"|"saved"|"rejected"|"applied";type Provider="greenhouse"|"lever"|"ashby";type RunStatus="running"|"succeeded"|"failed";
export interface Database{public:{Tables:{
profiles:{Row:{id:string;full_name:string|null;school:string|null;degree_program:string|null;graduation_year:number|null;location:string|null;created_at:string;updated_at:string};Insert:{id:string;full_name?:string|null;school?:string|null;degree_program?:string|null;graduation_year?:number|null;location?:string|null;created_at?:string;updated_at?:string};Update:{full_name?:string|null;school?:string|null;degree_program?:string|null;graduation_year?:number|null;location?:string|null;updated_at?:string};Relationships:[]};
job_preferences:{Row:{user_id:string;desired_titles:string[];desired_locations:string[];remote_preference:string;employment_types:string[];minimum_salary:number|null;preferred_industries:string[];preferred_skills:string[];excluded_keywords:string[];sponsorship_required:boolean;created_at:string;updated_at:string};Insert:{user_id:string;desired_titles?:string[];desired_locations?:string[];remote_preference?:string;employment_types?:string[];minimum_salary?:number|null;preferred_industries?:string[];preferred_skills?:string[];excluded_keywords?:string[];sponsorship_required?:boolean;created_at?:string;updated_at?:string};Update:{desired_titles?:string[];desired_locations?:string[];remote_preference?:string;employment_types?:string[];minimum_salary?:number|null;preferred_industries?:string[];preferred_skills?:string[];excluded_keywords?:string[];sponsorship_required?:boolean;updated_at?:string};Relationships:[]};
jobs:{Row:{id:string;external_id:string|null;source:string;source_id:string|null;source_url:string;application_url:string|null;company:string;title:string;description:string;location:string;workplace_type:string|null;employment_type:string|null;salary_min:number|null;salary_max:number|null;salary_currency:string|null;compensation_interval:string;skills:string[];seniority:string|null;sponsorship:boolean|null;posted_at:string|null;discovered_at:string;last_seen_at:string|null;is_active:boolean;created_at:string;updated_at:string;raw_payload:Json|null;content_hash:string|null};Insert:{id?:string;external_id?:string|null;source:string;source_id?:string|null;source_url:string;application_url?:string|null;company:string;title:string;description:string;location:string;workplace_type?:string|null;employment_type?:string|null;salary_min?:number|null;salary_max?:number|null;salary_currency?:string|null;compensation_interval?:string;skills?:string[];seniority?:string|null;sponsorship?:boolean|null;posted_at?:string|null;discovered_at?:string;last_seen_at?:string|null;is_active?:boolean;created_at?:string;updated_at?:string;raw_payload?:Json|null;content_hash?:string|null};Update:Record<string,unknown>;Relationships:[]};
user_job_statuses:{Row:{user_id:string;job_id:string;status:Status;applied_at:string|null;created_at:string;updated_at:string};Insert:{user_id:string;job_id:string;status?:Status;applied_at?:string|null;created_at?:string;updated_at?:string};Update:{status?:Status;applied_at?:string|null;updated_at?:string};Relationships:[]};
job_sources:{Row:{id:string;provider:Provider;company_name:string;board_identifier:string;enabled:boolean;careers_url:string|null;last_scanned_at:string|null;last_success_at:string|null;last_error:string|null;created_at:string;updated_at:string};Insert:{id?:string;provider:Provider;company_name:string;board_identifier:string;enabled?:boolean;careers_url?:string|null;last_scanned_at?:string|null;last_success_at?:string|null;last_error?:string|null;created_at?:string;updated_at?:string};Update:Record<string,unknown>;Relationships:[]};
ingestion_runs:{Row:{id:string;source_id:string;started_at:string;completed_at:string|null;status:RunStatus;fetched_count:number;inserted_count:number;updated_count:number;deactivated_count:number;error_message:string|null};Insert:{id?:string;source_id:string;started_at?:string;completed_at?:string|null;status?:RunStatus;fetched_count?:number;inserted_count?:number;updated_count?:number;deactivated_count?:number;error_message?:string|null};Update:Record<string,unknown>;Relationships:[]}
};Views:Record<string,never>;Functions:Record<string,never>;Enums:{job_status:Status;job_source_provider:Provider;ingestion_run_status:RunStatus};CompositeTypes:Record<string,never>}}
