"use server";import{revalidatePath}from"next/cache";import{createClient}from"@/lib/supabase/server";import{requireUser}from"@/lib/auth";import{supabaseJobRepository}from"@/lib/jobs";import{evaluateBatchForUser,evaluateJobForUser,HardIneligibleError}from"@/lib/evaluations/service";import type{EmploymentType,JobStatus,UserSettings,WorkArrangement}from"@/types/job";
import{runRecommendationsForUser}from"@/lib/recommendations/run";
export type ActionResult={ok:true;message:string}|{ok:false;message:string};
export async function updateJobStatus(jobId:string,status:JobStatus):Promise<ActionResult>{try{const user=await requireUser();await supabaseJobRepository.setStatus(user.id,jobId,status);revalidatePath("/jobs");revalidatePath(`/jobs/${jobId}`);return{ok:true,message:"Job status saved."}}catch{return{ok:false,message:"We could not save that change. Please try again."}}}
const list=(value:FormDataEntryValue|null)=>String(value??"").split(",").map(item=>item.trim()).filter(Boolean);
export async function saveSettings(formData:FormData):Promise<ActionResult>{try{const user=await requireUser(),supabase=await createClient(),yearValue=String(formData.get("graduationYear")??"").trim(),salaryValue=String(formData.get("minimumSalary")??"").trim();const graduationYear=yearValue?Number(yearValue):null,minimumSalary=salaryValue?Number(salaryValue):null;if(graduationYear!==null&&(!Number.isInteger(graduationYear)||graduationYear<1950||graduationYear>2100))return{ok:false,message:"Enter a valid graduation year."};if(minimumSalary!==null&&(!Number.isFinite(minimumSalary)||minimumSalary<0))return{ok:false,message:"Minimum salary must be zero or greater."};const now=new Date().toISOString();const profile={id:user.id,full_name:String(formData.get("fullName")??"").trim()||null,school:String(formData.get("school")??"").trim()||null,degree_program:String(formData.get("degreeProgram")??"").trim()||null,graduation_year:graduationYear,location:String(formData.get("location")??"").trim()||null,updated_at:now};const preferences={user_id:user.id,desired_titles:list(formData.get("desiredTitles")),desired_locations:list(formData.get("desiredLocations")),remote_preference:String(formData.get("remotePreference")??"flexible"),employment_types:formData.getAll("employmentTypes").map(String),minimum_salary:minimumSalary,preferred_industries:list(formData.get("preferredIndustries")),preferred_skills:list(formData.get("preferredSkills")),excluded_keywords:list(formData.get("excludedKeywords")),sponsorship_required:formData.get("sponsorshipRequired")==="on",updated_at:now};const[{error:profileError},{error:preferencesError}]=await Promise.all([supabase.from("profiles").upsert(profile),supabase.from("job_preferences").upsert(preferences)]);if(profileError||preferencesError)throw new Error();revalidatePath("/settings");return{ok:true,message:"Profile and preferences saved."}}catch{return{ok:false,message:"We could not save your settings. Please try again."}}}
export async function getSettings(userId:string):Promise<UserSettings>{const supabase=await createClient();const[{data:profile,error:profileError},{data:preferences,error:preferencesError}]=await Promise.all([supabase.from("profiles").select("*").eq("id",userId).maybeSingle(),supabase.from("job_preferences").select("*").eq("user_id",userId).maybeSingle()]);if(profileError||preferencesError)throw new Error("Unable to load your profile right now.");return{profile:{fullName:profile?.full_name??"",school:profile?.school??"",degreeProgram:profile?.degree_program??"",graduationYear:profile?.graduation_year??null,location:profile?.location??""},preferences:{desiredTitles:preferences?.desired_titles??[],desiredLocations:preferences?.desired_locations??[],remotePreference:(preferences?.remote_preference??"flexible")as WorkArrangement|"flexible",employmentTypes:(preferences?.employment_types??[])as EmploymentType[],minimumSalary:preferences?.minimum_salary??null,preferredIndustries:preferences?.preferred_industries??[],preferredSkills:preferences?.preferred_skills??[],excludedKeywords:preferences?.excluded_keywords??[],sponsorshipRequired:preferences?.sponsorship_required??false}}}
export async function evaluateJobAction(jobId:string):Promise<ActionResult>{try{const user=await requireUser();await evaluateJobForUser(user.id,jobId);revalidatePath("/jobs");revalidatePath(`/jobs/${jobId}`);return{ok:true,message:"Personalized evaluation saved."}}catch(error){return{ok:false,message:error instanceof HardIneligibleError?`Not evaluated: ${error.reasons.join("; ")}`:error instanceof Error?error.message:"Evaluation failed."}}}
export async function evaluateBatchAction(jobIds:string[]):Promise<ActionResult>{try{const user=await requireUser(),results=await evaluateBatchForUser(user.id,jobIds.slice(0,25)),succeeded=results.filter(x=>x.ok).length;revalidatePath("/jobs");return{ok:true,message:`Evaluated ${succeeded} of ${results.length} jobs.`}}catch{return{ok:false,message:"The evaluation batch could not be completed."}}}
export async function evaluateTopJobsAction():Promise<ActionResult>{try{const user=await requireUser(),result=await runRecommendationsForUser(user.id);revalidatePath("/jobs");return{ok:true,message:`Considered ${result.considered}; evaluated ${result.evaluated}, reused ${result.cacheReused}, and excluded ${result.hardExcluded}.`}}catch{return{ok:false,message:"The recommendation scan could not be completed."}}}
