import { createClient } from "@/lib/supabase/server";
import type { CandidateData } from "@/types/job";
import type { CandidatePartialDate } from "@/types/job";

function partialDate(row:Record<string,unknown>,prefix:string,isPresent=false):CandidatePartialDate {const year=typeof row[`${prefix}_year`] === "number"?row[`${prefix}_year`] as number:null,month=typeof row[`${prefix}_month`] === "number"?row[`${prefix}_month`] as number:null,day=typeof row[`${prefix}_day`] === "number"?row[`${prefix}_day`] as number:null,raw=typeof row[`${prefix}_raw`] === "string"?row[`${prefix}_raw`] as string:null;return{precision:isPresent?"present":day!==null?"day":month!==null?"month":year!==null?"year":"unknown",year,month,day,raw};}

export async function getCandidateData(userId:string):Promise<CandidateData>{const db=await createClient();const [profile,skills,experiences,projects,education,resumes]=await Promise.all([
  db.from("candidate_profiles").select("*").eq("user_id",userId).maybeSingle(),db.from("candidate_skills").select("*").eq("user_id",userId).order("skill_name"),
  db.from("candidate_experiences").select("*").eq("user_id",userId).order("start_date",{ascending:false}),db.from("candidate_projects").select("*").eq("user_id",userId).order("start_date",{ascending:false}),
  db.from("candidate_education").select("*").eq("user_id",userId).order("graduation_date",{ascending:false}),db.from("candidate_resumes").select("id,original_filename,uploaded_at,parsed_at,parsing_status,parsing_error,extraction").eq("user_id",userId).order("uploaded_at",{ascending:false}).limit(1).maybeSingle()
]);const failure=[profile,skills,experiences,projects,education,resumes].find(result=>result.error);if(failure?.error)throw new Error("Unable to load candidate profile.");const p=profile.data,r=resumes.data?.extraction&&!Array.isArray(resumes.data.extraction)&&typeof resumes.data.extraction==="object"?resumes.data.extraction as Record<string,unknown>:undefined,l=r?.links&&!Array.isArray(r.links)&&typeof r.links==="object"?r.links as Record<string,unknown>:{};return{profile:{professionalSummary:p?.professional_summary??"",yearsExperience:p?.years_experience??null,workAuthorization:p?.work_authorization??"",requiresSponsorship:p?.requires_sponsorship??null,preferredRoleLevel:p?.preferred_role_level??"",githubUrl:p?.github_url??"",linkedinUrl:p?.linkedin_url??"",portfolioUrl:p?.portfolio_url??""},skills:(skills.data??[]).map(x=>({id:x.id,skillName:x.skill_name,proficiency:x.proficiency??"",yearsExperience:x.years_experience,source:x.source,confirmed:x.confirmed})),experiences:(experiences.data??[]).map(x=>({id:x.id,organization:x.organization,title:x.title,startDate:partialDate(x,"start"),endDate:partialDate(x,"end",x.is_current),isCurrent:x.is_current,location:x.location??"",description:x.description??"",skills:x.skills,source:x.source,confirmed:x.confirmed})),projects:(projects.data??[]).map(x=>({id:x.id,name:x.name,description:x.description??"",technologies:x.technologies,projectUrl:x.project_url??"",repositoryUrl:x.repository_url??"",startDate:partialDate(x,"start"),endDate:partialDate(x,"end"),source:x.source,confirmed:x.confirmed})),education:(education.data??[]).map(x=>({id:x.id,institution:x.institution,degree:x.degree??"",programs:x.programs,graduationDate:partialDate(x,"graduation"),coursework:x.coursework,gpa:x.gpa,source:x.source,confirmed:x.confirmed})),resume:resumes.data?{id:resumes.data.id,originalFilename:resumes.data.original_filename,uploadedAt:resumes.data.uploaded_at,parsedAt:resumes.data.parsed_at,parsingStatus:resumes.data.parsing_status,parsingError:resumes.data.parsing_error,importedProfile:r?{professionalSummary:typeof r.summary==="string"?r.summary:"",githubUrl:typeof l.github==="string"?l.github:"",linkedinUrl:typeof l.linkedin==="string"?l.linkedin:"",portfolioUrl:typeof l.portfolio==="string"?l.portfolio:""}:undefined}:null}}
