import{AUTO_EVALUATION_SAFETY_CAP}from"./config";
import type{JobEvaluation}from"@/types/job";import{isRecommended}from"./config";import type{RecommendationState}from"./ranking";
export interface RecommendationCandidate{jobId:string;active:boolean;stale:boolean;hardEligible:boolean;prefilterScore:number;hasValidEvaluation:boolean;validEvaluationRecommended?:boolean;dismissed?:boolean}
export interface RecommendationRunResult{considered:number;hardExcluded:number;belowThreshold:number;selected:number;evaluated:number;cacheReused:number;failures:{jobId:string;message:string}[]}
export interface DiscoveryStateUpdate{prefilterScore:number;requested:boolean;evaluated:boolean;recommendationState:RecommendationState;error?:string}
export async function runRecommendationSelection(candidates:RecommendationCandidate[],options:{limit:number;threshold:number;evaluate:(jobId:string)=>Promise<{cached:boolean;evaluation:JobEvaluation}>;persist:(jobId:string,state:DiscoveryStateUpdate)=>Promise<void>}):Promise<RecommendationRunResult>{
  const limit=Math.min(AUTO_EVALUATION_SAFETY_CAP,Math.max(0,options.limit)),result:RecommendationRunResult={considered:candidates.length,hardExcluded:0,belowThreshold:0,selected:0,evaluated:0,cacheReused:0,failures:[]};
  const selected:RecommendationCandidate[]=[];
  for(const item of candidates.sort((a,b)=>b.prefilterScore-a.prefilterScore)){if(item.dismissed)continue;if(!item.active||item.stale||!item.hardEligible){result.hardExcluded++;await options.persist(item.jobId,{prefilterScore:item.prefilterScore,requested:false,evaluated:false,recommendationState:"excluded"});continue}if(item.hasValidEvaluation){result.cacheReused++;await options.persist(item.jobId,{prefilterScore:item.prefilterScore,requested:false,evaluated:false,recommendationState:item.validEvaluationRecommended?"recommended":"evaluated"});continue}if(item.prefilterScore<options.threshold){result.belowThreshold++;await options.persist(item.jobId,{prefilterScore:item.prefilterScore,requested:false,evaluated:false,recommendationState:"new"});continue}if(selected.length<limit)selected.push(item);else await options.persist(item.jobId,{prefilterScore:item.prefilterScore,requested:false,evaluated:false,recommendationState:"candidate"})}
  result.selected=selected.length;for(const item of selected){try{const value=await options.evaluate(item.jobId);if(value.cached)result.cacheReused++;else result.evaluated++;await options.persist(item.jobId,{prefilterScore:item.prefilterScore,requested:true,evaluated:!value.cached,recommendationState:isRecommended(value.evaluation)?"recommended":"evaluated"})}catch(error){const message=error instanceof Error?error.message:"Evaluation failed";result.failures.push({jobId:item.jobId,message});await options.persist(item.jobId,{prefilterScore:item.prefilterScore,requested:true,evaluated:false,recommendationState:"failed",error:message})}}
  return result;
}
