import"server-only";import{createClient}from"@/lib/supabase/server";import{getCandidateData}from"@/lib/candidate/repository";import{candidateProfileHash}from"@/lib/candidate/hash";import{EVALUATION_PROMPT_VERSION}from"@/lib/ai/prompts";import{evaluateJobForUserDetailed}from"@/lib/evaluations/service";import{getPreferences}from"@/lib/jobs";import{evaluateEligibility}from"@/lib/ingestion/eligibility";import{prefilterJob}from"./prefilter";import{isRecommended,recommendationConfig}from"./config";import{runRecommendationSelection}from"./engine";import type{EmploymentType,Job,JobEvaluation,WorkArrangement}from"@/types/job";import type{Json}from"@/types/database";
const category=(raw:Json|null)=>raw&&!Array.isArray(raw)&&typeof raw==="object"&&typeof raw.category==="string"?raw.category:"Other";
export async function runRecommendationsForUser(userId:string,requestedLimit=recommendationConfig.autoEvaluationLimit){
 const db=await createClient(),started=new Date().toISOString(),{data:run,error:runError}=await db.from("recommendation_runs").insert({user_id:userId,started_at:started}).select("id").single();if(runError)throw new Error("Unable to start recommendation run.");
 try{const[candidate,preferences,{data:rows,error:jobsError}]=await Promise.all([getCandidateData(userId),getPreferences(userId),db.from("jobs").select("*").eq("is_active",true).order("discovered_at",{ascending:false}).limit(recommendationConfig.candidateScanLimit)]);if(jobsError)throw new Error("Unable to load recommendation candidates.");
 const jobs=(rows??[]).map((row):Job=>({id:row.id,externalId:row.external_id??undefined,source:row.source,sourceId:row.source_id??undefined,sourceUrl:row.source_url,applyUrl:row.application_url??undefined,company:row.company,title:row.title,description:row.description,category:category(row.raw_payload),location:row.location,workArrangement:row.workplace_type as WorkArrangement|undefined,employmentType:row.employment_type as EmploymentType|undefined,salaryMin:row.salary_min??undefined,salaryMax:row.salary_max??undefined,salaryCurrency:row.salary_currency??undefined,compensationInterval:row.compensation_interval as Job["compensationInterval"],skills:row.skills,seniority:row.seniority??undefined,sponsorship:row.sponsorship??undefined,postedAt:row.posted_at??undefined,discoveredAt:row.discovered_at,status:"new",isActive:row.is_active,contentHash:row.content_hash??undefined}));
 const profileHash=candidateProfileHash({candidate,preferences}),ids=jobs.map(x=>x.id),[{data:evaluations},{data:discovery}]=await Promise.all([ids.length?db.from("job_evaluations").select("*").eq("user_id",userId).in("job_id",ids).order("created_at",{ascending:false}):Promise.resolve({data:[]}),ids.length?db.from("user_job_discovery").select("job_id,recommendation_state").eq("user_id",userId).in("job_id",ids):Promise.resolve({data:[]})]),valid=new Map<string,JobEvaluation>();for(const row of evaluations??[]){if(valid.has(row.job_id)||row.candidate_profile_hash!==profileHash||row.prompt_version!==EVALUATION_PROMPT_VERSION||row.job_content_hash!==jobs.find(j=>j.id===row.job_id)?.contentHash)continue;valid.set(row.job_id,{overallScore:row.overall_score,skillScore:row.skill_score,experienceScore:row.experience_score,educationScore:row.education_score,interestScore:row.interest_score,locationScore:row.location_score,compensationScore:row.compensation_score,recommendation:row.recommendation,verdict:row.verdict,summary:row.summary,matchingSkills:row.matching_skills,missingSkills:row.missing_skills,strengths:row.strengths,concerns:row.concerns,requirementGaps:row.requirement_gaps})}const dismissed=new Set((discovery??[]).filter(x=>x.recommendation_state==="dismissed").map(x=>x.job_id));
 const candidates=jobs.map(job=>{const hard=evaluateEligibility(job,preferences),prefilter=prefilterJob(job,preferences,candidate),age=(Date.now()-new Date(job.postedAt??job.discoveredAt).getTime())/86_400_000,evaluation=valid.get(job.id);return{jobId:job.id,active:job.isActive!==false,stale:age>90,hardEligible:hard.eligible,prefilterScore:prefilter.score,hasValidEvaluation:Boolean(evaluation),validEvaluationRecommended:evaluation?isRecommended(evaluation):false,dismissed:dismissed.has(job.id),reasons:prefilter.reasons}}),reasonMap=new Map(candidates.map(x=>[x.jobId,x.reasons]));
 const result=await runRecommendationSelection(candidates,{limit:requestedLimit,threshold:recommendationConfig.aiPrefilterThreshold,evaluate:jobId=>evaluateJobForUserDetailed(userId,jobId),persist:async(jobId,state)=>{const{error}=await db.rpc("update_recommendation_discovery",{p_job_id:jobId,p_prefilter_score:state.prefilterScore,p_prefilter_reasons:reasonMap.get(jobId)??[],p_recommendation_state:state.recommendationState,p_requested:state.requested,p_evaluated:state.evaluated,p_error:state.error?.slice(0,1000)??null});if(error)throw new Error("Unable to update recommendation discovery state.")}});
 await db.from("recommendation_runs").update({completed_at:new Date().toISOString(),status:result.failures.length?"partial":"succeeded",considered_count:result.considered,hard_excluded_count:result.hardExcluded,below_threshold_count:result.belowThreshold,selected_count:result.selected,evaluated_count:result.evaluated,cache_reused_count:result.cacheReused,failure_count:result.failures.length,error_message:result.failures.length?`${result.failures.length} evaluation(s) failed.`:null}).eq("id",run.id);return result
 }catch(error){await db.from("recommendation_runs").update({completed_at:new Date().toISOString(),status:"failed",error_message:(error instanceof Error?error.message:"Recommendation run failed").slice(0,1000)}).eq("id",run.id);throw error}
}
