"use server";
import { createHash } from "node:crypto";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { OpenAiProvider,AiConfigurationError,AiServiceError } from "@/lib/ai/provider";
import { resumeImportPayload } from "@/lib/candidate/import";
import { parseResumeDateInput } from "@/lib/candidate/resume-date";
import { extractPdfText } from "@/lib/resume/extract-pdf";
import type { ActionResult } from "@/app/actions";

const string=(data:FormData,name:string)=>String(data.get(name)??"").trim();const list=(value:string)=>value.split(",").map(x=>x.trim()).filter(Boolean);const dateColumns=(prefix:string,value:string)=>{const parsed=parseResumeDateInput(value,true);return{[`${prefix}_date`]:parsed.precision==="day"?`${parsed.year}-${String(parsed.month).padStart(2,"0")}-${String(parsed.day).padStart(2,"0")}`:null,[`${prefix}_year`]:parsed.year,[`${prefix}_month`]:parsed.month,[`${prefix}_day`]:parsed.day,[`${prefix}_raw`]:parsed.raw}};
function logCandidateError(operation:string,error:unknown){const value=error&&typeof error==="object"?error as Record<string,unknown>:{};console.error("Candidate action failed",{operation,code:value.code,message:value.message,details:value.details,hint:value.hint});}
export async function saveCandidateProfile(data:FormData):Promise<ActionResult>{try{const user=await requireUser(),db=await createClient(),years=string(data,"yearsExperience");const{error}=await db.from("candidate_profiles").upsert({user_id:user.id,professional_summary:string(data,"professionalSummary")||null,years_experience:years?Number(years):null,work_authorization:string(data,"workAuthorization")||null,requires_sponsorship:string(data,"requiresSponsorship")==="yes"?true:string(data,"requiresSponsorship")==="no"?false:null,preferred_role_level:string(data,"preferredRoleLevel")||null,github_url:string(data,"githubUrl")||null,linkedin_url:string(data,"linkedinUrl")||null,portfolio_url:string(data,"portfolioUrl")||null});if(error)throw error;revalidatePath("/profile");return{ok:true,message:"Candidate profile saved."}}catch{return{ok:false,message:"The candidate profile could not be saved."}}}
type Kind="skill"|"experience"|"project"|"education";
export async function saveCandidateItem(kind:Kind,data:FormData):Promise<ActionResult>{try{const user=await requireUser(),db=await createClient(),id=string(data,"id")||undefined;let result;if(kind==="skill"){const value={skill_name:string(data,"skillName"),proficiency:string(data,"proficiency")||null,years_experience:string(data,"yearsExperience")?Number(string(data,"yearsExperience")):null,confirmed:true};result=id?await db.from("candidate_skills").update(value).eq("id",id).eq("user_id",user.id):await db.from("candidate_skills").insert({...value,user_id:user.id,source:"manual"});}else if(kind==="experience"){const current=data.get("isCurrent")==="on",value={organization:string(data,"organization"),title:string(data,"title"),...dateColumns("start",string(data,"startDate")),...dateColumns("end",current?"Present":string(data,"endDate")),is_current:current,location:string(data,"location")||null,description:string(data,"description")||null,skills:list(string(data,"skills")),confirmed:true};result=id?await db.from("candidate_experiences").update(value).eq("id",id).eq("user_id",user.id):await db.from("candidate_experiences").insert({...value,user_id:user.id,source:"manual"});}else if(kind==="project"){const value={name:string(data,"name"),description:string(data,"description")||null,technologies:list(string(data,"technologies")),project_url:string(data,"projectUrl")||null,repository_url:string(data,"repositoryUrl")||null,...dateColumns("start",string(data,"startDate")),...dateColumns("end",string(data,"endDate")),confirmed:true};result=id?await db.from("candidate_projects").update(value).eq("id",id).eq("user_id",user.id):await db.from("candidate_projects").insert({...value,user_id:user.id,source:"manual"});}else{const value={institution:string(data,"institution"),degree:string(data,"degree")||null,programs:list(string(data,"programs")),...dateColumns("graduation",string(data,"graduationDate")),coursework:list(string(data,"coursework")),gpa:string(data,"gpa")?Number(string(data,"gpa")):null,confirmed:true};result=id?await db.from("candidate_education").update(value).eq("id",id).eq("user_id",user.id):await db.from("candidate_education").insert({...value,user_id:user.id,source:"manual"});}if(result.error)throw result.error;revalidatePath("/profile");return{ok:true,message:"Candidate information saved."}}catch(error){logCandidateError(`save ${kind}`,error);return{ok:false,message:"That candidate item could not be saved."}}}
export async function deleteCandidateItem(kind:Kind,id:string):Promise<ActionResult>{try{const user=await requireUser(),db=await createClient();const result=kind==="skill"?await db.from("candidate_skills").delete().eq("id",id).eq("user_id",user.id):kind==="experience"?await db.from("candidate_experiences").delete().eq("id",id).eq("user_id",user.id):kind==="project"?await db.from("candidate_projects").delete().eq("id",id).eq("user_id",user.id):await db.from("candidate_education").delete().eq("id",id).eq("user_id",user.id);if(result.error)throw result.error;revalidatePath("/profile");return{ok:true,message:"Item deleted."}}catch(error){logCandidateError(`delete ${kind}`,error);return{ok:false,message:"That item could not be deleted."}}}
export async function confirmCandidateItem(kind:Kind,id:string):Promise<ActionResult>{try{await requireUser();const db=await createClient(),rpc=db.rpc as unknown as (name:string,args:{p_kind:Kind;p_id:string})=>Promise<{data:string|null;error:unknown}>;const result=await rpc("confirm_candidate_item",{p_kind:kind,p_id:id});if(result.error||result.data!==id)throw result.error??new Error("Confirmed row was not returned");revalidatePath("/profile");const label=kind[0].toUpperCase()+kind.slice(1);return{ok:true,message:`${label} confirmed.`}}catch(error){logCandidateError(`confirm ${kind}`,error);return{ok:false,message:"The item could not be confirmed."}}}
export async function uploadAndParseResume(data:FormData):Promise<ActionResult>{const user=await requireUser(),file=data.get("resume");if(!(file instanceof File)||file.type!=="application/pdf")return{ok:false,message:"Choose a PDF resume."};if(file.size>10*1024*1024)return{ok:false,message:"Resume PDFs must be 10 MB or smaller."};const bytes=new Uint8Array(await file.arrayBuffer()),hash=createHash("sha256").update(bytes).digest("hex"),path=`${user.id}/${hash}.pdf`,db=await createClient();const{error:uploadError}=await db.storage.from("resumes").upload(path,bytes,{contentType:file.type,upsert:true});if(uploadError)return{ok:false,message:"The private resume upload failed."};const{data:resume,error:metadataError}=await db.from("candidate_resumes").upsert({user_id:user.id,storage_path:path,original_filename:file.name,mime_type:file.type,content_hash:hash,parsing_status:"parsing",parsing_error:null},{onConflict:"storage_path"}).select("id").single();if(metadataError||!resume)return{ok:false,message:"Resume metadata could not be saved."};try{const text=await extractPdfText(bytes);const extraction=(await new OpenAiProvider().parseResume(text)).data;const{error:persistenceError}=await db.rpc("persist_resume_import",{p_resume_id:resume.id,p_extracted_text:text.slice(0,100_000),p_extraction:resumeImportPayload(extraction)});if (persistenceError) {
    console.error("Resume persistence error",{code:persistenceError.code,message:persistenceError.message,details:persistenceError.details,hint:persistenceError.hint});
    throw new Error(
      "Resume parsing completed, but the imported data could not be saved."
    );
  }revalidatePath("/profile");return{ok:true,message:"Resume parsed. Review and confirm imported information below."}}catch(error){const message=error instanceof AiConfigurationError?error.message:error instanceof AiServiceError?error.message:error instanceof Error?error.message:"Resume parsing failed.";const{error:statusError}=await db.from("candidate_resumes").update({parsing_status:"failed",parsing_error:message.slice(0,500)}).eq("id",resume.id).eq("user_id",user.id);revalidatePath("/profile");return{ok:false,message:statusError?`${message} The failure status could not be saved.`:message}}
}

export async function acceptResumeProfile():Promise<ActionResult>{try{const user=await requireUser(),db=await createClient();const{data:resume,error}=await db.from("candidate_resumes").select("extraction").eq("user_id",user.id).eq("parsing_status","parsed").order("parsed_at",{ascending:false}).limit(1).maybeSingle();if(error||!resume?.extraction||Array.isArray(resume.extraction)||typeof resume.extraction!=="object")throw new Error();const extraction=resume.extraction as Record<string,unknown>,links=extraction.links&&!Array.isArray(extraction.links)&&typeof extraction.links==="object"?extraction.links as Record<string,unknown>:{},summary=typeof extraction.summary==="string"&&extraction.summary.trim()?extraction.summary:undefined,github=typeof links.github==="string"&&links.github.trim()?links.github:undefined,linkedin=typeof links.linkedin==="string"&&links.linkedin.trim()?links.linkedin:undefined,portfolio=typeof links.portfolio==="string"&&links.portfolio.trim()?links.portfolio:undefined;const{error:saveError}=await db.from("candidate_profiles").upsert({user_id:user.id,...(summary?{professional_summary:summary}:{}),...(github?{github_url:github}:{}),...(linkedin?{linkedin_url:linkedin}:{}),...(portfolio?{portfolio_url:portfolio}:{})});if(saveError)throw saveError;revalidatePath("/profile");return{ok:true,message:"Imported profile fields accepted."}}catch{return{ok:false,message:"Imported profile fields could not be accepted."}}}
